### ISSUE TITLE
to filter process_map according Case ID

### ISSUE THREAD

**Issue by Sedat1982** [bupaverse/bupaR#11]
Hello, i can filter process map according to activities, but is it possible to filter process_map according to only one specific Case ID?
thank you..

**Comment by gertjanssenswillen** [comment]
You can use the following: 

```
data %>%
    filter_case(cases = "your_case_id") %>%
    process_map()
```

`filter_case` is a function from package edeaR

**Comment by Sedat1982** [comment]
thank you, it worked :)
