### ISSUE TITLE
filtering cases according to the FLOW of activites

### ISSUE THREAD

**Issue by Sedat1982** [bupaverse/bupaR#13]
Hello,
if I want to filter the cases which have B and D acitivites, I can use filter_activity_presence(c("B", "D")). But,  how can I filter the cases which have 2 activities  **flow** only (from B to D direction) , like red row in the attachment.  is there a way to filter only this 5 cases? Thank you.

![Screenshot_1](https://user-images.githubusercontent.com/60322501/80891217-5aedb900-8ccb-11ea-86f9-419de4371fdc.png)

**Comment by gertjanssenswillen** [comment]
You can use the filter_precedence function for this. 

`filter_precedence("B","D")`

Note that you don't provide the 2 activities as a vector, but as two different arguments. They are named antecedent and consequent. 

You can choose whether B and D should directly follow (default) by setting precedency_type to "directly_follows". An alternative is to use "eventually_follows", where other activities are allowed in between.

**Comment by Sedat1982** [comment]
thank you so much for answer
