### ISSUE TITLE
Name of process discovery algorithm in bupaR

### ISSUE THREAD

**Issue by rensl88** [bupaverse/bupaR#28]
First of all, thanks for your work with this package, has been very helpful so far. 

This is actually more a general question than it is an issue: I was wondering wat kind of process mining algorithm is implemented in bupaR as the general process discovery algorithm. To me,  it looks like the basic alpha miner, but I'm not sure. Just curious because I'm doing a little research in the available process mining algorithms included in open source languages/tools.

**Comment by gertjanssenswillen** [comment]
The main way to visualize processes in bupaR is the "process map", which is a directly-follows graph (DFG). It is an actual representation of the log, there is no algorithm behind it that filters or generalizes the data - each sequence of two tasks in the log is represented by an arrow between nodes. It is similar to the graphs shown by (e.g.) Disco (https://fluxicon.com/disco/)

This will generally lead to a complex graph. Different from Disco (and others) is that there are no sliders to simplify the graph. Instead, we will require users to use plain filters to perform their own simplifications of the graph. The rationale is that the user knows exactly how the visual is simplified - it is not some magical filter under the hood, thereby providing 100% transparancy. 

Apart from that, process discovery algorithms that are provided by the ecosystem:
- the heuristics miner  (https://github.com/bupaverse/heuristicsmineR)

algorithms that are provided through the PM4PY bridge (https://github.com/bupaverse/pm4py):
- alpha miner 
- inductive miner

Feel free to get in touch if you have further questions.

**Comment by rensl88** [comment]
Thanks! That perfectly answers my question.

**Comment by fmannhardt** [comment]
Let me know if there are issues with the PM4Py Bridge. I have not tried it a while and should update it to the latest version of PM4Py (pull requests appreciated)
