### ISSUE TITLE
arrange() unexpected behavior

### ISSUE THREAD

**Issue by Erinaceida** [bupaverse/bupaR#33]
when using arrange(X, decreasing= T), bupaR version of the function doesn't throw an error but still doesn't reverse the arrangement, or when two variables are selected for arranging, produces an odd, mixed arrangement that makes little sense.

**Comment by fmannhardt** [comment]
The `arrange` function is based on the original dply` function here:
https://dplyr.tidyverse.org/reference/arrange.html

There is no `decreasing` parameter in dplyr (as opposite to the standard R `order`). You need to use `desc` as in the dplyr documentation to get a order by decreasing values.
