### ISSUE TITLE
i cant create event log.

### ISSUE THREAD

**Issue by Sedat1982** [bupaverse/bupaR#4]
Hello, for 3 days i try to create an event log with a csv log file. but it fails. i couldnt find a solution in internet. the problem is, when i try to creat event log, it doesnt report any problem. but when i run str(data), it shows that my data is still data.frame not eventlog.

my csv data; the name is logb1.csv
patient,activity,timestamp,status,activity_instance,resource
A,Atamalar,2016-04-06T15:56:37Z,Completed,1,Veli
A,Analiz,2016-04-08T16:06:29Z,Finish,2,Ali
A,Fonksiyonel Test,2016-04-10T16:12:04Z,Finish,3,Onur
A,Son Kullanici Test,2016-04-12T16:15:45Z,Finish,4,Serdar
A,Dagitim Onayi,2016-05-14T06:00:48Z,Finish,5,Kemal
A,Canliya Gecis,2016-05-16T07:00:48Z,Finish,6,Mehmet
A,Basarili Kapatildi,2016-05-18T09:00:48Z,Finish,7,Osman

the codes that i run after i installed all packages;
data = read.csv("logb1.csv")
data$timestamp = as.POSIXct(data$`timestamp`)
> data %>% #a data.frame with the information in the table above
+     eventlog(
+         case_id = "patient",
+         activity_id = "activity",
+         activity_instance_id = "activity_instance",
+         lifecycle_id = "status",
+         timestamp = "timestamp",
+         resource_id = "resource"
+     )
Log of 7 events consisting of:
1 trace 
1 case 
7 instances of 7 activities 
7 resources 
Events occurred from 2016-04-06 until 2016-05-18 
 
Variables were mapped as follows:
Case identifier:		patient 
Activity identifier:		activity 
Resource identifier:		resource 
Activity instance identifier:	activity_instance 
Timestamp:			timestamp 
Lifecycle transition:		status 

# A tibble: 7 x 7
  patient activity         timestamp           status    activity_instan… resource .order
  <chr>   <fct>            <dttm>              <fct>     <chr>            <fct>     <int>
1 A       Atamalar         2016-04-06 00:00:00 Completed 1                Veli          1
2 A       Analiz           2016-04-08 00:00:00 Finish    2                Ali           2
3 A       Fonksiyonel Test 2016-04-10 00:00:00 Finish    3                Onur          3
4 A       Son Kullanici T… 2016-04-12 00:00:00 Finish    4                Serdar        4
5 A       Dagitim Onayi    2016-05-14 00:00:00 Finish    5                Kemal         5
6 A       Canliya Gecis    2016-05-16 00:00:00 Finish    6                Mehmet        6
7 A       Basarili Kapati… 2016-05-18 00:00:00 Finish    7                Osman         7

As you see, after i run the event log function, it doesnt report any problem. but when i run str(data), it still looks as data.frame, not eventlog.

and so when i try to run activity_frequency function, it gives this problem below,

data %>% 
  activity_frequency(level = "activity") %>% 
  plot()

Error in UseMethod("activity_frequency") :    no applicable method for 'activity_frequency' applied to an object of class "data.frame"
--
 How it doesnt change to eventlog from dataframe?

Thanks and Regards.

**Comment by gertjanssenswillen** [comment]
I think the problem is that you don't save the created event log to a variable. The ´data´ object is therefore still a data.frame indeed. 

Try the following (note the difference in the first line).

```
data <- data %>% #a data.frame with the information in the table above

eventlog(
    case_id = "patient",
    activity_id = "activity",
    activity_instance_id = "activity_instance",
    lifecycle_id = "status",
    timestamp = "timestamp",
    resource_id = "resource"
)
```

**Comment by Sedat1982** [comment]
it worked :) thank you so much for your clear and fast answer. i got a cold for a few days so i couldnt check here.
Regards.
