### ISSUE TITLE
perf issue question 

### ISSUE THREAD

**Issue by chalioui** [bupaverse/bupaR#6]
Thank you for this great package! Do you have some benchmarks about the performance of the package? what if we have billions of case ids? Maybe switching to data. table help?

**Comment by gertjanssenswillen** [comment]
We don't have any benchmarks at the moment. Performance will be an issue with billions of case ids, without a doubt. We are looking into ways to use data.table internally (for some part we already to), as well as in the api. See also https://github.com/bupaverse/processmapR/issues/13
