### ISSUE TITLE
activity_instance value

### ISSUE THREAD

**Issue by Sedat1982** [bupaverse/bupaR#7]
Hello Gert,
İ was reading buparnet i have a question about activity_instance. i searched in google but couldnt find a clear answer. when we assign number to activity_instance values in the log table, in which order can we do it?
in some articles people do it according to the case_id, in some article they do it according to the lifecycle_id and some do it to activities?  for instance, i give some examples below. which model is right from these tables below. ? 1., 2. or 3. table? in which order we should set activity_instance numbers? Thank you.

1. TABLE

patient | activity | timestamp | status | activity_instance
-- | -- | -- | -- | --
A | check-in | 5/10/2017   8:33 | complete | 1
A | surgery | 5/11/2017   8:33 | schedule | 2
A | surgery | 5/12/2017   8:33 | start | 2
A | surgery | 5/13/2017   8:33 | complete | 2
B | check-in | 5/14/2017   8:33 | complete | 3
B | surgery | 5/15/2017   8:33 | schedule | 4
B | surgery | 5/16/2017   8:33 | start | 4
B | surgery | 5/17/2017   8:33 | complete | 4

2. TABLE

patient | activity | timestamp | status | activity_instance
-- | -- | -- | -- | --
A | check-in | 5/10/2017   8:33 | complete | 1
A | surgery | 5/11/2017   8:33 | schedule | 2
A | surgery | 5/12/2017   8:33 | start | 2
A | surgery | 5/13/2017   8:33 | complete | 2
B | check-in | 5/14/2017   8:33 | complete | 1
B | surgery | 5/15/2017   8:33 | schedule | 2
B | surgery | 5/16/2017   8:33 | start | 2
B | surgery | 5/17/2017   8:33 | complete | 2

3. TABLE

patient | activity | timestamp | status | activity_instance
-- | -- | -- | -- | --
A | check-in | 5/10/2017   8:33 | complete | 1
A | surgery | 5/11/2017   8:33 | schedule | 2
A | surgery | 5/12/2017   8:33 | start | 3
A | surgery | 5/13/2017   8:33 | complete | 4
B | check-in | 5/14/2017   8:33 | complete | 5
B | surgery | 5/15/2017   8:33 | schedule | 6
B | surgery | 5/16/2017   8:33 | start | 7
B | surgery | 5/17/2017   8:33 | complete | 8

**Comment by gertjanssenswillen** [comment]
The order of the activity instance has no meaning. It is a key. It can even be a unique string instead of unique numbers. 

Each event with the same value belongs together. From the examples above, I'd say the first one is probably the most correct one, but the others are not per definition wrong - i depends on your data. 

But to answer your question: each unique activity instance should combine events that belong to an execution of an activity, and they aren't ordered.
